apps/accounts/urls.py
from django.conf.urls import url

from apps.accounts.views import (
    LoginView,
    LogoutView
)


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

apps/overseer/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.overseer import views


urlpatterns = [
    url(r'^$', login_required(views.Index.as_view()), name='index'),
    url(r'^upload_data/$', login_required(views.UploadJsonDataView.as_view()), name='submit-file'),
    url(r'^upload_raw_data/$', login_required(views.UploadRawDataView.as_view()), name='submit-raw-file'),
    url(r'^get_matches/$', views.get_matches, name="get_matches"),
    url(r'^get_approved_matches/$', views.get_approved_matches, name="get_approved_matches"),
    url(r'^get_reverse_matches/$', views.get_reverse_matches, name="get_reverse_matches"),
    url(r'^get_normalized_details/$', views.get_normalized_details, name="get_normalized_details"),
    url(r'^get_aliases/$', views.get_aliases, name="get_aliases"),
    url(r'^get_discarded/$', views.get_discarded, name="get_discarded"),
    url(r'^get_skipped/$', views.get_skipped, name="get_skipped"),
    url(r'^matchstrings_form_submit/$', views.matchstrings_form_submit, name="matchstrings_form_submit"),
    url(r'^makealias_form_submit/$', views.makealias_form_submit, name="makealias_form_submit"),
    url(r'^makeapproved_form_submit/$', views.makeapproved_form_submit, name="makeapproved_form_submit"),
    url(r'^addnew_inst_form_submit/$', views.addnew_inst_form_submit, name="addnew_inst_form_submit"),
    url(r'^addnew_alias_form_submit/$', views.addnew_alias_form_submit, name="addnew_alias_form_submit")
    
]

config/urls.py
"""
Hammer URL Configuration
"""


from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
	## App urls
    url(r'^', include('apps.accounts.urls', namespace='accounts')),
    url(r'^', include('apps.overseer.urls', namespace='overseer')),

    ## Admin urls
    url(r'^manage/', admin.site.urls),
]

templates/partials/add_new_alias_form.html
{% block add_new_alias %}	
	<div id="alias-modal" class="alias-modal">
	  <!-- Modal content -->
		<div class="modal-content">
			<span class="closed">×</span>
			{# <p>Some text in the Modal..</p> #}
			<div class="add-new-alias-form-container">
				<h4> Add New Alias </h4>
				<form id="add-new-alias-form" class="add-new-alias-form" action="" method="POST">
				{% csrf_token %}
					<ul>
						<input type="hidden" id="inst_id" name="inst_id" value="234"></input>
						<li><div class="form-field-name">Alias Name :</div><input type="text" id="alias-name" name="alias-name" value=''></input></li>
						<li><button class="button-primary" type="submit" id="submit_alias_form">Submit</button></li>
					</ul>
				</form>
			</div>
		</div>
	</div>
{% endblock add_new_alias %}

templates/partials/add_new_form.html
{% block add_new %}	
	<div id="myModal" class="modal">
	  <!-- Modal content -->
		<div class="modal-content">
			<span class="close">×</span>
			<div class="add-new-form-container">
				<h4> Add New Institute </h4>
				<form id="add-new-form" class="add-new-form" action="#" method="POST">
				{% csrf_token %}
					<ul>
						<li><div class="form-field-name">Institute Name :</div><input type="text" id="inst_name" name="inst_name" value=''></input></li>
						<li><div class="form-field-name">City :</div><input type="text" id="city" name="city" value=''></input></li>
						<li><div class="form-field-name">State:</div><input type="text" id="state" name="state" value=''></input></li>
						<li><div class="form-field-name">Country:</div> <input type="text" id="country" name="country" value='India'></input></li>
						<li><div class="form-field-name">Established Year:</div> <input type="text" id="est" name="est" value=''></input></li>
						<li><div class="form-field-name">Institute Type:</div> 
							<select name="inst_type">
							    {% for inst in inst_types %}
								    <option value="{{ inst }}">{{ inst }}</option>
								{% endfor %}
							 </select>
						</li>
						{# <input type="text" id="inst_type" name="inst_type" value=''></input> #}
						<li><div class="form-field-name">Extra Info:</div> <input type="text" id="extra_info" name="extra_info" value=''></input></li>
						<li><button class="button-primary" type="submit" id="submit_form">Submit</button></li>
					</ul>
				</form>
			</div>
		</div>
	</div>
{% endblock add_new %}

templates/partials/header.html
<div class="header">
    <nav class="navbar">
        <div class="container">
            {# <div class="upload_norm_data"> #}
            <ul class="navbar-list icons-nav u-pull-left">
                {% if upload_form %}
                <li class="navbar-item">
                    <form class="upload_form" method="POST" action="{% url 'overseer:submit-file' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ upload_form }}
                    </form>
                    <a class="navbar-link icon" href="#" id="upload_link"><span class="iconicfill-cloud-upload"></span></a>
                </li>
                {% endif %} 
            </ul>
            {# </div> #}
            {# <div class="upload_unnorm_data"> #}
            <ul class="navbar-list icons-nav u-pull-left">
                {% if upload_form %}
                <li class="navbar-item">
                    <form class="upload_raw_form" method="POST" action="{% url 'overseer:submit-raw-file' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ upload_form }}
                    </form>
                    <a class="navbar-link icon" href="#" id="raw_upload_link"><span class="iconicfill-cloud-upload"></span></a>
                </li>
                {% endif %} 
            </ul>
            {# </div> #}          

            {# <div class="logout"> #}
            <ul class="navbar-list text-nav u-pull-right">
                {% if user.is_authenticated %}
                <li class="navbar-item">
                {{ user.username }}, 
                    <a class="navbar-link" href="{% url 'accounts:logout' %}">
                            Logout
                    </a>
                </li>
                {% endif %}
            </ul>
            {# </div> #}
        </div>
    </nav>
</div>

templates/partials/notifications.html
{% if form.errors %}
    <div class="notifications error">
        <a class="navbar-link icon cross" href="#"><span class="iconicfill-x"></span></a>
        {% for field in form %}
            {% if field.errors %}
                <p><strong>{{ field.name|title }}:</strong> {{ field.errors.0 }}</p>                 {% endif %}
        {% endfor %}
        
        <p class="non-field">{{ form.non_field_errors.0 }}</p>
    </div>
{% endif %}
{% if upload_form.errors %}
    <div class="notifications error">
        <a class="navbar-link icon cross" href="/"><span class="iconicfill-x"></span></a>
        {% for field in upload_form %}
            {% if field.errors %}
                <p><strong>{{ field.name|title }}:</strong> {{ field.errors.0 }}</p>                 {% endif %}
        {% endfor %}
        <p class="non-field">{{ upload_form.non_field_errors.0 }}</p>
    </div>
{% endif %}
{% if messages %}
    <a class="navbar-link icon" href="/"><span class="iconicfill-x"></span></a>
    {% for message in messages %}
    <div class="notifications {{ message.tags }}">
        <p>{{ message }}</p>
    </div>
    {% endfor %}
{% endif %}

templates/partials/pagination.html
{% load hammer_filters %}

<div class="paginate">	
	<span class="prev-arrow">
	{% if page.has_previous %}
		{% with page_value=page.number|add:"-1" %}
			{% with page_str=page_value|pageno %}
			<a href="{{request.GET|handle_get_params:page_str}}"><<  </a>
			{% endwith %}
		{% endwith %}
	{% endif %}
	</span>

	<span class="page-list">
	{% with min=page.number|add:"-6" max=page.number|add:"6" %}
		{% for x in paginator.page_range %}
			{% if x > min and x < page.number %}
				{% with page_str=x|pageno %}
					<a href="{{request.GET|handle_get_params:page_str}}">{{ x }}</a>
				{% endwith %}
			{% endif %}
		{% endfor %}
		{{page.number}}
		{% for x in paginator.page_range %}
			{% if x > page.number and x < max %}
				{% with page_str=x|pageno %}
					<a href="{{request.GET|handle_get_params:page_str}}">{{ x }}</a>
				{% endwith %}
			{% endif %}
		{% endfor %}
	{% endwith %}
	</span>

	<span class="next-arrow">
	{% if page.has_next %}
		{% with page_value=page.number|add:"1" %}
			{% with page_str=page_value|pageno %}
				<a href="{{request.GET|handle_get_params:page_str}}">  >></a>
			{% endwith %}
		{% endwith %}
	{% endif %}
	</span>
</div>

templates/partials/string_info.html
{% block string_info %}
    <div class ="right_container">
        <div class="match-list-container" id="match_list_container">
        
        </div>
    </div>
{% endblock string_info %}

templates/partials/tabs.html
{% load hammer_filters %}

{% block tabs %}
	<ul class="tab-list">
		{% for tab in tabtypes %}
			<li class="cls_tab {% if request.GET.type == tab %}active{% endif %}{% if not request.GET.type and tab == 'matches' %}active{% endif %}" id="{{tab}}">
				<a href="?type={{tab}}" data-type="{{tab}}">{{tab|title}}</a>
			</li>
		{% endfor %}
	</ul>
	<ul class="object-list cls_tab_content" id="normalized">

		<div class="search-box" id="search-box">
            <form class="search_form" id="search_form" method="GET" action="#"> 
	            {% if norm_list == 1 %}
	                <input type="hidden" name="type" value="matches">
	            {% elif norm_list == 2 %}
	                <input type="hidden" name="type" value="approved matches">
	            {% elif norm_list == 3 %}
	            	<input type="hidden" name="type" value="reverse matches">
	            {% else %}
	            	<input type="hidden" name="type" value="unmatched">
	            {% endif %}
	            <span class="fontawesome-search"></span>
	            <input type="text" id="search_text" name="searched" value="Search Here"></input>
                <button type="submit" class="search-button" id="search-button">Search</button>
            </form>
        </div>
        <div class="add-new-container">		
			{% if norm_list == 1 and user_group == 1 %}
				<a class="add-new icon" href="#" id="add-new"><span class="iconicfill-plus-alt"> Add New</span></a>
			{% endif %}
		</div>
		{% for result in page %}
			{% if norm_list == 1 %}
				<a href="javascript:void(0)" id="{{ result.id }}" class="cls_string_name" data-string-type="norm" data-group-id="{{ user_group }}">
			{% elif norm_list == 2 %}
				<a href="javascript:void(0)" id="{{ result.id }}" class="cls_string_name" data-string-type="approved" data-group-id="{{ user_group }}">
			{% elif norm_list == 3 %}
				<a href="javascript:void(0)" id="{{ result.id }}" class="cls_string_name" data-string-type="reverse_match" data-group-id="{{ user_group }}">
			{% else %}	
				<a href="javascript:void(0)" id="{{ result.id }}" class="cls_string_name" data-string-type="unnorm" data-group-id="{{ user_group }}">
			{% endif %}
				<div class="string-name">
					<div class="string-name-container">
						<li>{{ result.name }}</li>
					</div>
					</a>
					<div class="match-text-container">
						{% if norm_list == 1 %}
							<p>{{ result.cummulative_matches}} Cummulative Matches Found</p>
							<p>{{ result.no_of_matches}} Unique Matches Found</p>
						{% elif norm_list == 2 %}
							<p>{{ result.no_of_approved_matches}} Approved Matches Found</p>
						{% elif norm_list == 3 %}
							<p>Frequency: {{ result.frequency}}</p>
							<p> {{ result.no_of_matches}} Unique Matches Found</p>
						{% elif norm_list == 4 %}
							<p>Frequency: {{ result.frequency}}</p>
						{% endif %}
					</div>
					{% if norm_list == 1 %}
						<div class="match-buttons" id="match-buttons">
							<button type="button" id="matches" data-result-id="{{ result.id }}" class="matches-button" data-group-id="{{ user_group }}">Unapproved</button>
							<button type="button" id="approved" data-result-id="{{ result.id }}" class="matches-button" data-group-id="{{ user_group }}">Approved</button>
							<button type="button" id="discarded" data-result-id="{{ result.id }}" class="matches-button" data-group-id="{{ user_group }}">Discarded</button>
							<button type="button" id="skipped" data-result-id="{{ result.id }}" class="matches-button" data-group-id="{{ user_group }}">Skipped</button>
							<button type="button" id="aliases" data-result-id="{{ result.id }}" class="matches-button" data-group-id="{{ user_group }}">Aliases</button>
						</div>
					{% endif %}
				</div>
		{% endfor %}
		{% include 'partials/pagination.html' %}
	</ul>
{% endblock tabs %}